# Generated by Django 4.0.5 on 2022-06-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('thumbUrl', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('tags', models.JSONField()),
            ],
        ),
    ]
